### ISSUE TITLE
NullPointerException when trying to obtain a market board response

### ISSUE THREAD

**Issue by lbkulinski** [rainbowdashlabs/universalis-java#95]
Hello!

Unfortunately I am back with another bug. This time, a `NullPointerException`. The stack trace is as follows;
```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "de.chojo.universalis.entities.views.CurrentlyShownView.listingViews()" is null
	at de.chojo.universalis.deserializer.response.MarketBoardResponseDeserializer.deserialize(MarketBoardResponseDeserializer.java:39) ~[universalis-rest-1.4.0.jar:na]
	at de.chojo.universalis.deserializer.response.MarketBoardResponseDeserializer.deserialize(MarketBoardResponseDeserializer.java:30) ~[universalis-rest-1.4.0.jar:na]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740) ~[jackson-databind-2.15.4.jar:2.15.4]
	at de.chojo.universalis.rest.UniversalisRestImpl.getAndMapInternal(UniversalisRestImpl.java:230) ~[universalis-rest-1.4.0.jar:na]
	at de.chojo.universalis.rest.UniversalisRestImpl.lambda$getAsyncAndMap$0(UniversalisRestImpl.java:203) ~[universalis-rest-1.4.0.jar:na]
```

The code I am using that causes this is as follows:
```
MarketBoardResponse response = this.universalisClient.marketBoard()
                                                     .dataCenter(dataCenter)
                                                     .itemsIds(itemId)
                                                     .highQuality(highQuality)
                                                     .queue()
                                                     .get();
```

I can try to open a PR to fix it, but not at the moment.

Thanks,
Logan

**Comment by lbkulinski** [comment]
While the NPE is still an issue, it seems like there is also an issue with the request URL causing the Universalis API to send back a 404. The request URL of the library is `https://universalis.app/api/v2/4/10?hq=true`, which responds with a 404. If you request data from `https://universalis.app/api/v2/Aether/10?hq=true`, though, you get back the expected response.

**Comment by rainbowdashlabs** [comment]
Thanks for the hint with the id. The api actually states that it can be either id or name, but I guess thats not true for datacenters at least.

I added a fix in the latest version.
